name = "ProjectHub"
uuid = "a718dd9f-36d6-437b-84fb-ed8b66e043bb"
authors = ["Francesco"]
version = "1.0.0-DEV"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3.7.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
